# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

    cache:
        pools:
            app.cache:
                adapter: 'cache.adapter.redis'
                provider: '%env(REDIS_URL)%'

when@test:
    framework:
        http_method_override: true
        test: true
        session:
            enabled: true
            storage_id: 'session.storage.native'
            handler_id: 'session.handler.native_file'
            save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
