version: '3.8'

services:
  # PHP 8.3 с Symfony
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app_network
    environment:
      - PHP_XDEBUG_MODE=off
    depends_on:
      - database
      - redis
      - rabbitmq

  # Nginx для работы с PHP
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  # Postgres 16
  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
